In [1]:
import numpy as np

In [49]:
a=np.ones(11)

In [47]:
m=a.size
a.shape

(11,)

In [30]:
b=np.stack([np.ones(m), a], axis=1)

In [35]:
np.sum(np.dot(a,b)-1)/2

10.0

In [61]:
np.linspace(10,100,91)

array([ 10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,
        21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,
        32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,
        43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,
        54.,  55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,
        65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,
        76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,
        87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,
        98.,  99., 100.])

In [62]:
a=np.ones((2,5))

In [65]:
np.mean(a,axis=0)

array([1., 1., 1., 1., 1.])

In [64]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])